# Generated by Django 5.1 on 2024-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cli', models.CharField(max_length=80, verbose_name='Nome do Cliente')),
                ('doc_cli', models.CharField(max_length=20, verbose_name='Documento')),
                ('fone_cli', models.CharField(max_length=12, verbose_name='Telefone')),
            ],
        ),
    ]
